#ifndef MISC_B_ZS
#define MISC_B_ZS

#define CURSOR_HEIGHT 3
#define CURSOR_WIDTH 3
#define BULLET_WIDTH 1
#define BULLET_HEIGHT 1

#define BUTTON_HEIGHT 19
#define BUTTON_WIDTH 64

extern const UINT32 SURVIVE_A[BUTTON_HEIGHT];
extern const UINT32 SURVIVE_B[BUTTON_HEIGHT];

extern const UINT8 CURSOR[CURSOR_HEIGHT];

#endif
