/*
 * Player bitmap.
 *
 * A player consists of two 32-bit bitmaps joined together
 * one on top of the other.
 *
 * The Upper Body:
 *     The upper body can be looking North, NorthEest, East,
 *     Southeast, South, Southwest or West.
 * The Lower body:
 *     The lower body can be looking North, East, West, South
 *     and can step left, right or be stopped.
 *
 */
#ifndef PLAYER_ZS
#define PLAYER_ZS

#define PLAYER_UPPER_BODY_HEIGHT 14
#define PLAYER_LOWER_BODY_HEIGHT 5
#define PLAYER_HEIGHT 19
#define PLAYER_WIDTH 18
#define PLAYER_TOTAL_STEPS 4
#define PLAYER_STEPS_STOP_NUMBER 1


#define MOVE_W 0
#define MOVE_N 1
#define MOVE_E 2
#define MOVE_S 3

#define LOOK_N  0
#define LOOK_NW 1
#define LOOK_W  2
#define LOOK_SW 3
#define LOOK_S  4
#define LOOK_SE 5
#define LOOK_E  6
#define LOOK_NE 7

extern const UINT32 PLAYER_DEAD[8];

extern const UINT32 PLAYER_UPPER_BODY_WEST[PLAYER_UPPER_BODY_HEIGHT];
extern const UINT32 PLAYER_UPPER_BODY_EAST[PLAYER_UPPER_BODY_HEIGHT];
extern const UINT32 PLAYER_UPPER_BODY_SOUTH[PLAYER_UPPER_BODY_HEIGHT];
extern const UINT32 PLAYER_UPPER_BODY_NORTH[PLAYER_UPPER_BODY_HEIGHT];
extern const UINT32 PLAYER_UPPER_BODY_NORTHWEST[PLAYER_UPPER_BODY_HEIGHT];
extern const UINT32 PLAYER_UPPER_BODY_NORTHEAST[PLAYER_UPPER_BODY_HEIGHT];
extern const UINT32 PLAYER_UPPER_BODY_SOUTHEAST[PLAYER_UPPER_BODY_HEIGHT];
extern const UINT32 PLAYER_UPPER_BODY_SOUTHWEST[PLAYER_UPPER_BODY_HEIGHT];

extern const UINT32 PLAYER_LOWER_BODY_EAST_STEP_ONE[PLAYER_LOWER_BODY_HEIGHT];
extern const UINT32 PLAYER_LOWER_BODY_EAST_STOP[PLAYER_LOWER_BODY_HEIGHT];
extern const UINT32 PLAYER_LOWER_BODY_EAST_STEP_TWO[PLAYER_LOWER_BODY_HEIGHT];

extern const UINT32 PLAYER_LOWER_BODY_WEST_STEP_ONE[PLAYER_LOWER_BODY_HEIGHT];
extern const UINT32 PLAYER_LOWER_BODY_WEST_STOP[PLAYER_LOWER_BODY_HEIGHT];
extern const UINT32 PLAYER_LOWER_BODY_WEST_STEP_TWO[PLAYER_LOWER_BODY_HEIGHT];

extern const UINT32 PLAYER_LOWER_BODY_NORTH_STEP_ONE[PLAYER_LOWER_BODY_HEIGHT];
extern const UINT32 PLAYER_LOWER_BODY_NORTH_STOP[PLAYER_LOWER_BODY_HEIGHT];
extern const UINT32 PLAYER_LOWER_BODY_NORTH_STEP_TWO[PLAYER_LOWER_BODY_HEIGHT];

extern const UINT32 *PLAYER_UPPER_BODY[8];
extern const UINT32 *PLAYER_STEP[4][PLAYER_TOTAL_STEPS];
#endif
