#ifndef PLAYER_ZS
#define PLAYER_ZS

#define PLAYER_BODY_HEIGHT 14
#define PLAYER_LEGS_HEIGHT 5

extern const UINT32 PLAYER_BODY_WEST[PLAYER_BODY_HEIGHT];
extern const UINT32 PLAYER_BODY_EAST[PLAYER_BODY_HEIGHT];
extern const UINT32 PLAYER_BODY_SOUTH[PLAYER_BODY_HEIGHT];
extern const UINT32 PLAYER_BODY_NORTH[32];
extern const UINT32 PLAYER_BODY_NORTHWEST[PLAYER_BODY_HEIGHT];
extern const UINT32 PLAYER_BODY_NORTHEAST[PLAYER_BODY_HEIGHT];
extern const UINT32 PLAYER_BODY_SOUTHEAST[PLAYER_BODY_HEIGHT];
extern const UINT32 PLAYER_BODY_SOUTHWEST[PLAYER_BODY_HEIGHT];
extern const UINT32 PLAYER_EAST_STEP_ONE[PLAYER_LEGS_HEIGHT];
extern const UINT32 PLAYER_EAST_STOP[PLAYER_LEGS_HEIGHT];
extern const UINT32 PLAYER_EAST_STEP_TWO[PLAYER_LEGS_HEIGHT];
extern const UINT32 PLAYER_WEST_STEP_ONE[PLAYER_LEGS_HEIGHT];
extern const UINT32 PLAYER_WEST_STOP[PLAYER_LEGS_HEIGHT];
extern const UINT32 PLAYER_WEST_STEP_TWO[PLAYER_LEGS_HEIGHT];
extern const UINT32 PLAYER_NORTH_STEP_ONE[PLAYER_LEGS_HEIGHT];
extern const UINT32 PLAYER_NORTH_STOP[PLAYER_LEGS_HEIGHT];
extern const UINT32 PLAYER_NORTH_STEP_TWO[PLAYER_LEGS_HEIGHT];
extern const UINT32 *PLAYER_BODY[8];
extern const UINT32 *PLAYER_STEP[4][3];

extern const int LOOK_N;
extern const int LOOK_NW;
extern const int LOOK_W;
extern const int LOOK_SW;
extern const int LOOK_S;
extern const int LOOK_SE;
extern const int LOOK_E;
extern const int LOOK_NE;

#endif
