#ifndef ZOMBIE_ZS
#define ZOMBIE_ZS
#define ZOMBIE_HEIGHT 24
extern const UINT32 ZOMBIE_WEST_STOP[ZOMBIE_HEIGHT];
extern const UINT32 ZOMBIE_WEST_STEP_ONE[ZOMBIE_HEIGHT];
extern const UINT32 ZOMBIE_WEST_STEP_TWO[ZOMBIE_HEIGHT];

extern const UINT32 ZOMBIE_EAST_STOP[ZOMBIE_HEIGHT];
extern const UINT32 ZOMBIE_EAST_STEP_ONE[ZOMBIE_HEIGHT];
extern const UINT32 ZOMBIE_EAST_STEP_TWO[ZOMBIE_HEIGHT];

extern const UINT32 ZOMBIE_NORTH_STOP[ZOMBIE_HEIGHT];
extern const UINT32 ZOMBIE_NORTH_STEP_ONE[ZOMBIE_HEIGHT];
extern const UINT32 ZOMBIE_NORTH_STEP_TWO[ZOMBIE_HEIGHT];

extern const UINT32 ZOMBIE_SOUTH_STOP[ZOMBIE_HEIGHT];
extern const UINT32 ZOMBIE_SOUTH_STEP_ONE[ZOMBIE_HEIGHT];
extern const UINT32 ZOMBIE_SOUTH_STEP_TWO[ZOMBIE_HEIGHT];

extern const UINT32 *ZOMBIE_DIRECTION_STEP[4][3];

extern const UINT Z_MOVE_W;
extern const UINT Z_MOVE_N;
extern const UINT Z_MOVE_E;
extern const UINT Z_MOVE_S;
#endif
